# create a SqlSvr that stores data in the container, not a volume

# ref: https://www.microsoft.com/en-us/sql-server/developer-get-started/python/mac

# sudo docker pull mcr.microsoft.com/mssql/server
# docker run --name sqlsvr -e 'HOMEBREW_NO_ENV_FILTERING=1' -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=posey386!' -p 1433:1433 -d mcr.microsoft.com/mssql/server


# Now set up your sqlsvr database

#    northwind - thanks, Doug: https://douglaskline.blogspot.com/2020/09/restoring-sql-server-db-backup-to.html
#       paste test data from tests/sql_server/northwind.sql
#    SampleDB
#       from tests/sql_server/SampleDB.sql


# Now convert container to image

# docker commit sqlsvr sqlsvr-image
# docker tag sqlsvr-image apilogicserver/sqlsvr:version1.0.0
# docker push apilogicserver/sqlsvr:version1.0.0


# accessing it...
# docker run --name sqlsvr-container --net dev-network -p 1433:1433 -d apilogicserver/sqlsvr:version1.0.0

# docker run -it --name api_logic_server --rm --net dev-network -p 5000:5000 -p 8080:8080 -v ${PWD}:/local/servers apilogicserver/api_logic_server

# ApiLogicServer create --project_name=/local/servers/sqlserver db_url=mssql+pyodbc://sa:posey386!@localhost:1433/NORTHWND?driver=ODBC+Driver+17+for+SQL+Server?trusted_connection=no

# ApiLogicServer create --project_name=/local/servers/sqlserver-types --db_url=mssql+pyodbc://sa:posey386\!@localhost:1433/SampleDB?driver=ODBC+Driver+17+for+SQL+Server?trusted_connection=no
# works with: SQLALCHEMY_DATABASE_URI = "mssql+pyodbc://sa:posey386!@localhost:1433/SampleDB?driver=ODBC+Driver+17+for+SQL+Server?trusted_connection=no"
# x ApiLogicServer create --project_name=/local/servers/sqlserver-types --db_url=mssql+pyodbc://sa:posey386\!@localhost:1433/SampleDB?driver=FreeTDS?trusted_connection=no