# create a mysql that stores data in the container, not a volume

# docker build -t apilogicserver/mysql --file Dockerfile-MySQL --rm .
# docker run --name mysql-container --net dev-network -p 3306:3306 -d -e MYSQL_ROOT_PASSWORD=p apilogicserver/mysql


# Now set up your mysql database

#    mysql --user root --password
#    paste test data, etc


# Now convert container to image

# docker commit mysql-container mysql-image
# docker tag mysql-image apilogicserver/mysql8.0:version1.0.6
# docker push apilogicserver/mysql8.0:version1.0.6


# accessing it...
# docker run --name mysql-container --net dev-network -p 3306:3306 -d -e MYSQL_ROOT_PASSWORD=p apilogicserver/mysql8.0:version1.0.6
# ApiLogicServer create --project_name=/local/servers/classicmodels --db_url=mysql+pymysql://root:p@mysql-container:3306/classicmodels

# thanks - https://medium.com/@stevenlandow/persist-share-dev-mysql-data-in-a-docker-image-with-commit-f9aa9910be0a

FROM mysql:8.0

RUN mkdir /var/lib/mysql-no-volume
CMD ["--datadir", "/var/lib/mysql-no-volume"]